@startuml
title クラス図

利用する -> 利用される

namespace Maps{
    class WorldMapState{
    }
    class LocalMapState{
    }
    class BattleState{
    }
    class MenuState{
    }

}

namespace Players{
    class PlayerStatusUI
    {    
        Text name;
        Text level;
        Text hp;
        Text mp;
        Text gold;
        Text ex;
        void UpdateUI();
    }

    class PlayerCore
    {
        // ステータスを持つだけ：関数は持たない
        string name;
        int level;
        int hp;
        int mp;
        int gold;
        int ex;
    }
    class PlayerAction
    {
        void Attack();
        void MagicAction();
        void Escape();
        void UseTool();
    }

    PlayerAction -> PlayerCore
    PlayerStatusUI -> PlayerCore
    PlayerCore ...|> Battlers.Battler

    UserInput -> PlayerAction 

    class UserInput
    {
        void OpenMenu();
    }
}


namespace Battles {

    class BattleManager
    {
        void Setup();
        void BattleEnd();
    }
    BattleManager ->Battlers.Battler
}
namespace Battlers {

    class Battler
    {
        int hp;
        int mp;
        int speed;
        int at;
        
        void Attack()
    }
    interface IDamageable
    {
        void OnDamage()
    }

    IDamageable <|-- Battler
}

namespace Menus{
    class CommandMenu
    {
    }

}

namespace GameManagers{

    enum GameMode
    {
        Battle,
        Field
    }

    class GameManager
    {
    }
}

namespace Enemys{

    Monster ...|> Battlers.Battler

    class Monster
    {
        // ステータスを持っている
    }

    class MonsterDatabase
    {
        void Spawn()
    }
}
@enduml